/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.equipo3.View;

import com.mycompany.equipo3.Model.Usuarios;
import com.mycompany.equipo3.Silvia;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author b15-08m
 */
public class BorrarTransaccion extends javax.swing.JPanel {

    private int idUsuario = 1;

    CamVis cv1;
    Usuarios usuario;
    private int idTransaccionSeleccionada;
    private JPanel jContenido;
    private JScrollPane jScrollPane;
    public BorrarTransaccion(CamVis cv1, Usuarios usuario, JPanel jContenido, JScrollPane jScrollPane) {
        this.cv1 = cv1;
        this.usuario = usuario;
        this.jContenido = jContenido;
        this.jScrollPane = jScrollPane;
        initComponents();
        lblNull.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnConectar = new java.awt.Button();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnModidicar = new javax.swing.JButton();
        lblNull = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(806, 411));

        jLabel1.setText("MIS INTERCAMBIOS");

        jLUsuario.setText("Pulse el botón para buscar sus intercambios");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConectar.setActionCommand("btnConectar");
        btnConectar.setLabel("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnModidicar.setText("Modificar");
        btnModidicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModidicarActionPerformed(evt);
            }
        });

        lblNull.setText("No tiene ningún intercambio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNull, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModidicar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLUsuario)
                                .addGap(149, 149, 149)
                                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLUsuario)
                    .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModidicar)
                    .addComponent(lblNull))
                .addGap(28, 28, 28))
        );

        btnConectar.getAccessibleContext().setAccessibleName("btnConectar");
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Silvia.borrarTransaccion(idTransaccionSeleccionada);
        jComboBox1.removeAllItems();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        lblNull.setVisible(false);
        ArrayList<String> consulta = Silvia.consultaTransaccionesUsuario(usuario.getUsuarioid());
        
        if(consulta==null){
            lblNull.setVisible(true);
        }else{
            for (int i = 0; i < consulta.size(); i++) {
                jComboBox1.addItem(consulta.get(i));
            }  
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Obtener el ítem seleccionado del JComboBox
            String itemSeleccionado = (String) jComboBox1.getSelectedItem();

            // Encontrar la posición del primer espacio en el texto
            int espacioIndex = itemSeleccionado.indexOf(' ');

            // Extraer la parte del texto correspondiente al ID de la transacción
            String idTransaccionString = itemSeleccionado.substring(0, espacioIndex);

            // Convertir el ID de transacción a entero
            idTransaccionSeleccionada = Integer.parseInt(idTransaccionString);
            }
        });
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnModidicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModidicarActionPerformed
        System.out.println("[TRAZA] BOTON");
        String id=jComboBox1.getSelectedItem().toString();
        id=id.split(" ")[0];
        
        JPanel nueva = new InserModiTrans(cv1, "Modificar", usuario, Integer.parseInt(id));
        
        jContenido.setLayout(new FlowLayout());
        jContenido.removeAll();
        jContenido.add(nueva);
        jContenido.revalidate();
        jContenido.repaint();
        if (!jContenido.isVisible()) {
            jContenido.setVisible(true);
        }
    }//GEN-LAST:event_btnModidicarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnConectar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModidicar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNull;
    // End of variables declaration//GEN-END:variables
}
